StatauIrPristatau/Controllers/Admin/MainAdminController.cs
using StatauIrPristatau.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StatauIrPristatau.Controllers.Admin
{
    public class MainAdminController : Controller
    {
        public ActionResult Details(int Id)
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                if (Session["UserId"] != null)
                {
                    var usr = db.userAccount.Single(u => u.Id == Id);
                    return View("~/Views/Admin/UserView.cshtml", usr);
                }
                else
                {
                    return View("~/Views/User/Login.cshtml");
                }

            }
        }

        [HttpPost]
        public ActionResult Edit(User account)
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                if (ModelState.IsValid)
                {
                    var result = db.userAccount.Single(u => u.Email.ToString() == account.Email.ToString());
                    if (result != null)
                    {
                        result.Name = account.Name;
                        result.Surname = account.Surname;
                        result.Password = account.Password;
                        result.YearOfBirth = account.YearOfBirth;
                        result.Address = account.Address;
                        db.SaveChanges();
                    }
               
                }
                return View("~/Views/Shared/MainView.cshtml", db.userAccount.ToList());
            }
        }

        public ActionResult Edit(int Id)
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                if (Session["UserId"] != null)
                {
                    var usr = db.userAccount.Single(u => u.Id == Id);
                    return View("~/Views/Admin/EditView.cshtml", usr);
                }
                else
                {
                    return View("~/Views/Shared/MainView.cshtml");
                }
            }
        }

        public ActionResult Delete(int Id)
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                if (Session["UserId"] != null)
                {
                    db.userAccount.Remove(db.userAccount.Single(a => a.Id == Id));
                    db.SaveChanges();
                }
                return View("~/Views/Shared/MainView.cshtml", db.userAccount.ToList());
            }
        }

        [Route("Registration")]
        public ActionResult Registration()
        {
            return View("~/Views/Admin/RegistrationScreen.cshtml");
        }


        public ActionResult ToMainView()
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                return View("~/Views/Shared/MainView.cshtml", db.userAccount.ToList());
            }
        }
    }
}

StatauIrPristatau/Controllers/Customer/CustomerController.cs
using Microsoft.Ajax.Utilities;
using StatauIrPristatau.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StatauIrPristatau.Controllers.Customer
{
    public class CustomerController : Controller
    {
        public ActionResult openCourierRatings(string searchString)
        {
            
            using (SIPDbContext db = new SIPDbContext())
            {
                if (!String.IsNullOrEmpty(searchString))
                {

                    var results = db.userAccount.Include(o => o.Rankings).Where(s => s.Email.Contains(searchString));
                  
                        
                    return View("~/Views/Customer/CourierRatingsView.cshtml", results.ToList());
                    
                }
                else
                {
                    var results = db.userAccount.Include(o => o.Rankings);
                    return View("~/Views/Customer/CourierRatingsView.cshtml", results.ToList());
                }

             
         
            }


        }
        [Route("openRatingsPop")]
        public ActionResult openRatingsPop()
        {
            PopulateDepartmentsDropDownList();
            return View("~/Views/Customer/openRatingsPop.cshtml");
        }
        [HttpPost]
        public ActionResult openRatingsPop(Ranking ranking)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SIPDbContext db = new SIPDbContext())
                    {
                        db.rankings.Add(ranking);
                        db.SaveChanges();
                        ModelState.Clear();
                        var results = db.userAccount.Include(o => o.Rankings);
                        return View("~/Views/Customer/CourierRatingsView.cshtml", results.ToList());
                    }
                }
                else
                {
                    return View("~/Views/Customer/openRatingsPop.cshtml");
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            PopulateDepartmentsDropDownList(ranking.DepartmentID);
            return View("~/Views/Customer/openRatingsPop.cshtml");
        }
            // GET: Customer
            public ActionResult openOrderedShipments()
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                var results = db.orders.Where(o => o.State != 3).Include(o => o.Parcels);
                return View("~/Views/Customer/ShipmentsView.cshtml", results.ToList());
            }
        }
        private void PopulateDepartmentsDropDownList(object selectedDepartment = null)
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                var departmentsQuery = from d in db.userAccount
                                       orderby d.Email
                                       select d;
                ViewBag.DepartmentID = new SelectList(departmentsQuery, "DepartmentID", "Email", selectedDepartment);
            }
        }

        public ActionResult openMap()
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                var results = db.orders.Where(o => o.State != 3).Include(o => o.Parcels);
                return View("~/Views/Customer/Map.cshtml", results.ToList());
            }
        }

        public JsonResult getPickUpAddress()
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                string[] currentOrder = new string[50];

                int k = 0;

                foreach (Parcel parcel in db.parcels)
                {
                    currentOrder[k] = parcel.Pickup_Address;
                    k++;
                }

                return Json(currentOrder, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult getDeliveryAddress()
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                string[] currentOrder = new string[50];

                int k = 0;

                foreach (Parcel parcel in db.parcels)
                {
                    currentOrder[k] = parcel.DeliveryAddress;
                    k++;
                }

                return Json(currentOrder, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult openNewOrder()
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                int Id = (int)System.Web.HttpContext.Current.Session["UserId"];
                User currentUser = db.userAccount.Single(u => u.Id == Id);
                Order order = new Order();
                order.User = currentUser;
                order.Date = DateTime.Now;
                db.orders.Add(order);
                db.SaveChanges();
                ModelState.Clear();
                return View("~/Views/Customer/OrderShipmentView.cshtml", order);
            }

        }

        [HttpGet]
        public ActionResult updateOrder(string id, string value)
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                int ordId = int.Parse(id);
                int state = int.Parse(value);
                Order currentOrder = db.orders.Include(o => o.Parcels).Single(o => o.Id == ordId);
                currentOrder.Parcels.Select(cO => { cO.State = 1; return cO; }).ToList();
                currentOrder.State = state;
                db.SaveChanges();
                return View("~/Views/Customer/OrderShipmentView.cshtml", currentOrder);
            }
        }

        public ActionResult openAddParcelForm(int id)
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                ViewData["Message"] = id;
                return View("~/Views/Customer/addParcelView.cshtml");
            }
        }

        [HttpPost]
        public ActionResult fillOrderData(int id, Parcel parcel)
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                if (ModelState.IsValid)
                {
                    Order currentOrder = db.orders.Single(o => o.Id == id);
                    Tuple<Order, Parcel> tpl1 = PriceController.calculatePrice(currentOrder, parcel);
                    currentOrder = tpl1.Item1;
                    parcel = tpl1.Item2;
                    currentOrder.Parcels.Add(parcel);
                    db.SaveChanges();
                    return View("~/Views/Customer/OrderShipmentView.cshtml", currentOrder);
                }
                else
                {
                    ViewData["Message"] = id;
                    return View("~/Views/Customer/addParcelView.cshtml");
                }


            }

        }
    }
}

StatauIrPristatau/Controllers/Customer/PriceController.cs
using StatauIrPristatau.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StatauIrPristatau.Controllers.Customer
{
    public class PriceController : Controller
    {
        public static Tuple<Order, Parcel> calculatePrice(Order order, Parcel parcel)
        {
            parcel.Size = calculateSize(parcel);
            order.TotalSize = calculateCapacity(order, parcel);
            order.TotalWeigth = calculateWeigth(order, parcel);
            parcel.Car = pickCarForDelivery(parcel);
            double standardParcelPrice = 1;
            double orderPrice = order.TotalPrice;
            if (orderPrice == 0)
            {
                orderPrice = 1;
            }
            double parcelPrice = standardParcelPrice;
            double koefSizeS = 1.65;
            double koefSizeM = 2.15;
            double koefSizeL = 2.98;
            double koefSizeXL = 3.87;
            double koefOrderSizex2 = 1.25;
            double koefOrderSizex3 = 1.45;
            double koefOrderSizex4 = 1.75;
            double koefWeigthx2 = 1.25;
            double koefWeigthx3 = 1.45;
            double koefWeigthx4 = 1.75;
            if (parcel.Size == "S")
            {
                parcelPrice = parcelPrice * koefSizeS;
            }
            if (parcel.Size == "M")
            {
                parcelPrice = parcelPrice * koefSizeM;
            }
            if (parcel.Size == "L")
            {
                parcelPrice = parcelPrice * koefSizeL;
            }
            if (parcel.Size == "XL")
            {
                parcelPrice = parcelPrice * koefSizeXL;
            }
            orderPrice = orderPrice + parcelPrice;
            parcel.Price = parcelPrice;
            if (order.TotalSize / 1000000 > 1 && order.TotalSize / 1000000 <= 2)
            {
                orderPrice = orderPrice * koefOrderSizex2;
            }
            else if (order.TotalSize / 1000000 > 2 && order.TotalSize / 1000000 <= 3)
            {
                orderPrice = orderPrice * koefOrderSizex3;
            }
            else if (order.TotalSize / 1000000 > 3 && order.TotalSize / 1000000 <= 4)
            {
                orderPrice = orderPrice * koefOrderSizex4;
            }
            if (order.TotalWeigth / 550 > 1 && order.TotalWeigth / 550 <= 2)
            {
                orderPrice = orderPrice * koefWeigthx2;
            }
            else if (order.TotalWeigth / 550 > 2 && order.TotalWeigth / 550 <= 3)
            {
                orderPrice = orderPrice * koefWeigthx3;
            }
            else if (order.TotalWeigth / 550 > 3 && order.TotalWeigth / 550 <= 4)
            {
                orderPrice = orderPrice * koefWeigthx4;
            }
            order.TotalPrice = orderPrice;
            return Tuple.Create(order, parcel);
        }

        private static string calculateSize(Parcel parcel)
        {
            double size = 0;
            string sizeChar = "S";
            size = parcel.Height * parcel.Length * parcel.Width;
            if (size <= 21800 && size > 0)
            {
                sizeChar = "S";
            }
            else if (size <= 46200 && size > 21800)
            {
                sizeChar = "M";
            }
            else if (size <= 100000 && size > 46200)
            {
                sizeChar = "L";
            }
            else if (size > 100000)
            {
                sizeChar = "XL";
            }
            return sizeChar;
        }

        private static double calculateCapacity(Order order, Parcel parcel)
        {
            double totalSize = order.TotalSize;
            double parcelSize = parcel.Height * parcel.Length * parcel.Width;
            totalSize += parcelSize;
            return totalSize;
        }
        private static double calculateWeigth(Order order, Parcel parcel)
        {
            double totalWeigth = order.TotalWeigth;
            double parcelWeigth = parcel.Weigth;
            return totalWeigth += parcelWeigth;

        }
        private static string pickCarForDelivery(Parcel parcel)
        {
            string car;
            if (parcel.Size == "S" || parcel.Size == "M" )
            {
                car = "Mini";
            }
            else if (parcel.Size == "L")
            {
                car = "Medium";
            }
            else
            {
                car = "Maxi";
            }
            return car;
        }
    }
}

StatauIrPristatau/Controllers/User/MainUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using StatauIrPristatau.Models;
using System.Web.Mvc;
using System.Data.Entity;

namespace StatauIrPristatau.Controllers
{
    public class MainUserController : Controller
    {
        // GET: MainUser
        public ActionResult openOrderHistory()
        {
            using (SIPDbContext db = new SIPDbContext())
            {
                var results = db.orders.Where(o => o.State == 3).Include(o => o.Parcels);
                return View("~/Views/User/OrderView.cshtml", results.ToList());
            }
        }
    }
}

StatauIrPristatau/Views/Customer/CourierRatingsView.cshtml
@model IEnumerable<StatauIrPristatau.Models.User>
<!DOCTYPE html>
<html>


<head>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Statau ir pristatau</title>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>

        table tbody tr:hover {
            background-color: #ffe0e0;
        }
    </style>
</head>
<body>


    <div>
        <div style="width: 100%">
            <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #c0392b">
                <a class="navbar-brand" href="#">Statau ir pristatau</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav" style="margin-left: auto">
                        <li class="nav-item">
                            @Html.ActionLink("Naudotojų sąrašas", "ToMainView", "MainAdmin", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Užsakymų istorija", "openOrderHistory", "MainUser", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Vykdomi užsakymai", "openOrderedShipments", "Customer", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Žemėlapis", "openMap", "Customer", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Vertinimas", "openCourierRatings", "Customer", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Atsijungti</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="container mt-5">
            <div>
                <h3>Kurjerių sąrašas</h3>
            </div>

            @using (Html.BeginForm())
    {
        <p>
            FiltriukasPagalEmail: @Html.TextBox("SearchString")
            <input type="submit" value="Search" />
        </p>
}
            <table class="table">
                <thead>
                    <tr style="background-color: #c0392b">
                        <th scope="col">#</th>
                        <th scope="col">El. Paštas</th>
                        <th scope="col">Bendras Užsakymo Vertinimas</th>
                        <th scope="col">Kurjerio požiūris</th>
                        <th scope="col">Siuntinio kokybė</th>
                        <th scope="col">Pristatymo greitis</th>
                    </tr>
                </thead>
                <tbody>
                    @{
        int i = 0;
        foreach (var user in Model)
        {
            i++;
            int u = 0;
            double sum = 0;
            double average = 0;
            double sum1 = 0;
            double average1 = 0;
            double sum2 = 0;
            double average2 = 0;
            double sum3 = 0;
            double average3 = 0;
                <tr>
                    <th scope="row">@i</th>
                    <td>@Html.DisplayFor(userItem => user.Email)</td>

                    @{foreach (var ranks in user.Rankings)

        {
            if (user.Rankings != null)
            {
                u++;

                double a = ranks.Overall;
                sum = sum + a;
                double b = ranks.CourierRanking;
                sum1 = sum1 + b;
                double c = ranks.ParcelQuality;
                sum2 = sum2 + c;
                double d = ranks.DeliveryTime;
                sum3 = sum3 + d;
            }
        }
                    }
                    @{ average = sum / u;}
                    @{ average1 = sum1 / u;}
                    @{ average2 = sum2 / u;}
                    @{ average3 = sum3 / u;}
                    <td>@Html.DisplayFor(userItem => average)</td>
                    <td>@Html.DisplayFor(userItem => average1)</td>
                    <td>@Html.DisplayFor(userItem => average2)</td>
                    <td>@Html.DisplayFor(userItem => average3)</td>
                </tr>
}
                    }
                    @Html.ActionLink("Sukurti naują vertinimą", "openRatingsPop", "Customer", null, new { @class = "btn px-4 py-2 mb-4 mt-2", @style = "background-color: #c0392b; color: white;" })

                 


                </tbody>
            </table>
        </div>
    </div>



</body>

StatauIrPristatau/Views/Customer/OrderShipmentView.cshtml
@model StatauIrPristatau.Models.Order
<!DOCTYPE html>
<html>

<head>
    @using StatauIrPristatau.Helpers
    @using StatauIrPristatau.Content
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Statau ir pristatau</title>
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    @Html.Resource(@<script src="@Url.Content("~/Scripts/johny.js")" type="text/javascript"></script>, "js")
    @Html.RenderResources("js")
</head>
<body>
    <div>
           <div style="width: 100%">
            <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #c0392b">
                <a class="navbar-brand" href="#">Statau ir pristatau</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav" style="margin-left: auto">
                        <li class="nav-item">
                            @Html.ActionLink("Naudotojų sąrašas", "ToMainView", "MainAdmin", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Užsakymų istorija", "openOrderHistory", "MainUser", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Vykdomi užsakymai", "openOrderedShipments", "Customer", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Žemėlapis", "openMap", "Customer", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Vertinimas", "openCourierRatings", "Customer", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link disabled" href="#">Atsijungti</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="container mt-5">
            <div>
                <h3>Naujas užsakymas</h3>
            </div>
        <div class="mt-4 text-center">
            <h4 id="success_mess"> </h4>
        </div>
        <table class="table">
             <thead>
                        <tr style="background-color: #c0392b">
                            <th scope="col" style="color: #ffffff">Užsakymas Nr. @Html.DisplayFor(modelItem => Model.Id) </th>
                            <th scope="col" style="color: #ffffff">Data: @Html.DisplayFor(modelItem => Model.Date)      Būsena: @Enum.GetName(typeof(ordStates), Model.State)</th>
                            <th scope="col" style="color: #ffffff">Kaina: @Html.DisplayFor(modelItem => Model.TotalPrice) € </th>
                        </tr>
                    </thead>
               <tbody>
                    @{int i = 0;
                        if (Model.Parcels != null)
                        {
                            foreach (var parcel in Model.Parcels)
                            {
                                i++;
                                if (i % 3 == 1)
                                {
                             @:<tr>
                             @:<div class="pricing-box-container">
                            }
                            <td>
                               <div class="pricing-box text-center">
                               <h5>Siunta nr: @Html.DisplayFor(parcelItem => parcel.Parcel_Id)</h5>
                               <p class="Siuntos kaina"><sup>€</sup>@Html.DisplayFor(parcelItem => parcel.Price)</p>
                               <ul class="features-list">
                                   <li><strong>Paėmimo adresas: </strong> @Html.DisplayFor(parcelItem => parcel.Pickup_Address)</li>
                                   <li><strong>Pristatymo adresas: </strong> @Html.DisplayFor(parcelItem => parcel.DeliveryAddress)</li>
                                   <li><strong>Būsena </strong>  @Enum.GetName(typeof(parcStates), parcel.State)</li>
                                   <li><strong>Apskaičiuotas dydis:  </strong> @Html.DisplayFor(parcelItem => parcel.Size)</li>
                                   <li><strong>Svoris:  </strong> @Html.DisplayFor(parcelItem => parcel.Weigth)</li>
                                   <li><strong>Parinktas automobilio tipas: </strong> @Html.DisplayFor(parcelItem => parcel.Car)</li>
                               </ul>
                               </div>
                            </td>
                                if (i % 3 == 0)
                                {
                                @:</tr>
                                @:</div>
                            }
                            }
                        }
                        if(Model.Parcels == null || Model.Parcels.Count == 0)
                        {
                            @:<tr><td><h4>Pridėkite siuntą prie užsakymo</h4></td></tr>
                        }
                    }
                        
                </tbody>
                </table>
                <div class="mt-4 text-center">
                    <p>Paspaudę mygtuką užsakyti, galėsite apmokėti siuntą. Siuntos kaina gali būti mažesnė nei viso užsakymo kaina, ji gali skirtis, jeigu jūsų siuntos tūris ar kiekis viršija vieno didžiausio automobilio ribas</p>
                    <input type="button" class="btn" style="background-color: #c0392b; color: white;" value="Pridėti siuntą" onclick="@("window.location.href='" + @Url.Action("openAddParcelForm", "Customer", new { id = Model.Id } ) + "'");" />
                    <a class="btn" style="background-color: #c0392b; color: white;" data-toggle="modal" data-target="#confirmEdit">Užsakyti</a>
                </div>

           </div>
        <div class="modal fade" id="confirmEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Mokėjimų sistema - PayCeKa</h5>
                        <div class="form-group">
                            <label for="bank_data">Sąskaitos duomenys</label>
                            <div class="input-group">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                <input type="text" class="form-control" onchange="dataChange()" id="bank_data">
                            </div>
                        </div>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Atgal">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">

                        <label id="bank_label" for="bank_data">  </label>
                        <button tyoe="submit"  onclick="payClick(@Model.Id)" class="btn" style="background-color: #c0392b; color: white;">Apmokėti</button>
                        <button type="button" id="close_modal" class="btn" data-dismiss="modal">Atgal</button>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
</html>